### ISSUE TITLE
Problem with PHP 5 

### ISSUE THREAD

**Issue by Pilik** [vince52/eBot-install-script#3]
I took the problem:
root@csgo74:/home# ./ebot-install.sh
Package libapache2-mod-php5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'libapache2-mod-php5' has no installation candidate

Could you tell me how can i fix this? =(

**Comment by SShadowS** [comment]
Same here on a fresh "Ubuntu 17.04 Server".

Installed Ubuntu in an empty VM (only change at install is to add "SSH Server" feature.)
On first boot i ran:
`sudo apt upgrade`

Rebooted

On second boot:
```
wget https://raw.githubusercontent.com/vince52/eBot-install-script/master/ebot-install.sh && chmod +x ebot-install.sh 
./ebot-install.sh

```

Got the:
...
Package libapache2-mod-php5 is not available, but is referred to by another package.
...

**Comment by Pilik** [comment]
@SShadowS I solve this problem using older version of Ubuntu.
I Tryed to manage on the new one, but spend so much time and can't.

**Comment by gravfu** [comment]
Hello, The version of PHP you need is PHP5.
But you can't install PHP5 with the last version of Ubuntu
