### ISSUE TITLE
WebSocket server crashed

### ISSUE THREAD

**Issue by TugaAnon** [vince52/eBot-install-script#4]
Hello, i am using ubuntu 14.04 and WebSocket server is not working can someone help me?
sorry new to this stuff
![image](https://user-images.githubusercontent.com/16416252/32416310-2dbb3268-c23f-11e7-830c-4b9a9f6913f6.png)

**Comment by gravfu** [comment]
I think It's an error with the version of websocket. 

Can you give me an access tout your dedicated server?

**Comment by TugaAnon** [comment]
now web socket is working but bot and websocket is ofline .
i am using amazon vps so is behind a NAT.
![image](https://user-images.githubusercontent.com/16416252/32582063-d63b74aa-c4e4-11e7-866b-e0a250071815.png)
how can i send you the access ?

**Comment by gravfu** [comment]
@TugaAnon Can you test? I made some changes in my script.
